// hello-notes-react/src/js/components/navigation.jsx
import React from 'react';

const Navigation = props => {
  const {
    newNote,
    view,
    onChange
  } = props;

  return (
    <nav className="w-12 h-full bg-app flex flex-col border-r border-gray-400">
      <button
        title="Add"
        onClick={newNote}>
        <i className="material-icons">add</i>
      </button>
      <button
        title="Notes"
        className={view === "notes" ? "bg-app_light" : ""}
        onClick={() => onChange("notes")}>
        <i className="material-icons">description</i>
      </button>
      <button
        title="Trash"
        className={view === "deleted" ? "bg-app_light" : ""}
        onClick={() => onChange("deleted")}>
        <i className="material-icons">delete</i>
      </button>
    </nav>
  );
}

export default Navigation;

// hello-notes-svelte/src/js/components/Navigation.svelte
<style>
  nav {
    display: flex;
    flex-direction: column;
    width: 3rem;
    height: 100%;
    border-style: solid;
    border-color: rgb(156, 163, 175);
    border-width: 0 1px 0 0;
    background-color: rgb(149, 184, 149);
  }

  button {
    padding: 0.25rem;
    height: 2rem;
    background-color: transparent;
    background-image: none;
    border-width: 0;
  }
</style>

<nav>
  <button title="Add">
    <i class="material-icons">add</i>
  </button>
  <button title="Notes">
    <i class="material-icons">description</i>
  </button>
  <button title="Deleted notes">
    <i class="material-icons">delete</i>
  </button>
  <button title="Categories">
    <i class="material-icons">turned_in</i>
  </button>
</nav>
